### PR TITLE
Fixing $exceptionHandler bug

### LINKED ISSUE #483: Uncaught TypeError: $exceptionHandler is not a function
function exceptionTrack($provide) {
  $provide.decorator('$exceptionHandler', ['$delegate', '$injector', function ($delegate, $injector) {
    var excTrack = function (error, cause) {
      var result = $delegate(error, cause);
      var $analytics = $injector.get('$analytics');
      if ($analytics.settings.trackExceptions) {
        $analytics.exceptionTrack(error, cause);
      }
      return result;
    }
  }]);
}

should be:

  function exceptionTrack($provide) {

    $provide.decorator('$exceptionHandler', ['$delegate', '$injector', function ($delegate, $injector) {
      return function (error, cause) {
        var result = $delegate(error, cause);
        var $analytics = $injector.get('$analytics');
        if ($analytics.settings.trackExceptions) {
          $analytics.exceptionTrack(error, cause);
        }
        return result;
      }
    }]);
  }

the missing return case 'Uncaught TypeError: $exceptionHandler is not a function' instead of the real exception when an exception is raised.

### PR DESCRIPTION
**Pull request by bcarroll22**
Just wanted to get this PR up since it hadn't been proposed yet. This fixes #483.

### CODE REVIEW

**Comment by timelf123** [comment]
Thank you!

**Comment by lookitsatravis** [comment]
@timelf123 any idea when this might get into a release? I'm currently referencing master, but I'd prefer not to. =)

**Comment by timelf123** [comment]
This is in the latest release

**Comment by lookitsatravis** [comment]
@timelf123 - It doesn't look like it. This was merged 7 days ago on June 8, but 1.1.0 was released on June 6 and doesn't include this patch. Repo tags and NPM say 1.1.0 is the latest as of this message.

**Comment by timelf123** [comment]
Well I'll be damned, you are right! Sorry for the confusion. I'll try to cut a release ASAP but no promises on when it will be

**Comment by odedniv** [comment]
This is what happens when you are used to writing in CoffeeScript... (forgot that return there 😞)

**Comment by timelf123** [comment]
Released in https://github.com/angulartics/angulartics/releases/tag/1.1.1

**Comment by Tim-Intellipharm** [comment]
After upgrading from angulartics v1.1.0 to v1.1.1 it has now started causing the `Uncaught TypeError: $exceptionHandler is not a function` error. I have downgraded back to v1.1.0 and I get the proper errors again. I am using angulartics for piwik and angular v1.5.7.

**Comment by zwacky** [comment]
same for me on 1.1.1. although 1.1.0 also throws `$exceptionHandler is not a function`.
I opened up a new issue for this (#488).

**Comment by brunocoelho** [comment]
Thanks guys, this bug was driving me crazy! `1.1.2` is working properly. @atungare
