### ISSUE TITLE
Uncaught TypeError: $exceptionHandler is not a function

### ISSUE THREAD

**Issue by zwacky** [angulartics/angulartics#488]
Hey yall

in version `1.1.0` and `1.1.1` i'm having this `Uncaught TypeError: $exceptionHandler is not a function` issue. It works well with `1.0.3` though.

There has been an issue of this exact problem (#483), but it's been resolved some weeks ago. Looks like it's back.

**Comment by odedniv** [comment]
Can you provide a stack trace?

**Comment by zwacky** [comment]
yeah sure, it's only a little vague. it happens when angulartics tries to log a javascript error, as it seems.
i'm using angular 1.5.5.

```
angular.js:17554 Uncaught TypeError: $exceptionHandler is not a function
    $apply @ angular.js:17554
    (anonymous function) @ angular.js:17850
    completeOutstandingRequest @ angular.js:5955
    (anonymous function) @ angular.js:6234
```

**Comment by odedniv** [comment]
I meant, do you know which line it happens in angulartics code? Is it on the $delegate? Can you run it with non-minified angulartics?

Also which version of angular-google-analytics are you using? (or are you using any other angulartics plugin).

I'm also using angular 1.5.5 and I can't reproduce the issue.

**Comment by zwacky** [comment]
when i use `'node_modules/angulartics/src/angulartics.js'` i don't get this problem...

but `'node_modules/angulartics/dist/angulartics.min.js'` throws the error. looks like the dist folder hasn't been regenerated?

**Comment by odedniv** [comment]
Seems like it wasn't built properly before release, I think it's something with the grunt configuration (I don't remember how I did it). You can try to figure it out or use the source file and minify yourself until it's fixed.

**Comment by timelf123** [comment]
Fixed with 1.1.2. :shit:
