### ISSUE TITLE
Not compatible with the angular-ui-router 1.0 beta (and maybe up) 

### ISSUE THREAD

**Issue by ericsun977** [angulartics/angulartics#518]
`TypeError: hookFn.call is not a function` error shows with `angular-ui-router#1.0.0-beta.1`

This patch https://github.com/angulartics/angulartics/pull/490 is no longer needed for the ui-router version 1.0 beta due to the changes of the Transition Hooks they made. 

Revert that PR should fix the problem.

**Comment by timelf123** [comment]
Unable to revert from webui and don't have time to fix right now but would review a PR. thanks for catching

**Comment by ericsun977** [comment]
Double checked the code, the `[]` has been removed. For some reason, I am pulling the old version. I apologize.
